[ZF-4] - Login page styling
zicht/admin-bundle pull request #33
Opened 2019-02-15 15:05 UTC by pknijff

2019-03-18 08:54 UTC, pknijff commented
Kleine kanttekening: aangezien hier niet gewerkt wordt met sass/zsass, is er gewoon plain css geschreven voor de styling. Dit i.v.m. de hoeveelheid meer tijd dat het kost en onnodige dependencies.

2019-03-18 15:32 UTC, Hangloozz commented on src/Zicht/Bundle/AdminBundle/Resources/public/style/admin-cms.css
> +  width:230px;
consequent spatie na de dubbele punt?

2019-03-18 15:33 UTC, Hangloozz commented on src/Zicht/Bundle/AdminBundle/Resources/public/style/admin-cms.css
> +  float:left;
Als er toch al geflexed wordt, dan misschien de float ook vervangen door een geflexte oplossing?

2019-03-18 15:35 UTC, Hangloozz commented on src/Zicht/Bundle/AdminBundle/Resources/public/style/login.css
> +  letter-spacing: 0.21px;
Uhhh.. :D  Geen idee of een browser veel kan met 2 cijfers achter de komma :P

2019-03-18 15:36 UTC, Hangloozz commented on src/Zicht/Bundle/AdminBundle/Resources/public/style/login.css
> +  text-shadow: 1px 4px 0 0 #7A7A7A, 1px 10px 0 0 #00ADDE, 0 0 40px 0 rgba(0,0,0,0.4);
Officieel spaties tussen getal en de komma

2019-03-18 15:37 UTC, Hangloozz commented on src/Zicht/Bundle/AdminBundle/Resources/public/style/login.css
> +  letter-spacing: 0.06px;
Idem, geen idee of dat echt werkt?

2019-03-18 15:39 UTC, Hangloozz commented on src/Zicht/Bundle/AdminBundle/Resources/public/style/login.css
> +  box-shadow: 0 2px 4px 0 rgba(0,0,0,0.2);
spates tussen getal en voorgaande komma

2019-03-18 15:42 UTC, Hangloozz commented on src/Zicht/Bundle/AdminBundle/Resources/views/sonata_layout.html.twig
> +        .logo span.cms_title {
Misschien dat deze lege declaratie weg mag, of is dat een placeholder voor mogelijke styling op projectbasis?

2019-04-18 12:50 UTC, Hangloozz requested changes
Zie commnets

2019-04-29 09:17 UTC, Hangloozz approved these changes

2019-04-29 09:17 UTC, merged